### PR TITLE
Fix PCL version to 1.9.1

### PR DESCRIPTION
**Pull request by margaritaG**
The latest devel version of PCL (current master branch) implementes the change described in https://github.com/PointCloudLibrary/pcl/issues/2792
That is, all Boost smart pointers are replaced with standard smart pointers. 

This seems to be breaking the compilation of the code in the pcl_catkin repository. (See e.g. https://jenkins.asl.ethz.ch/job/pcl_catkin_pull_requests/label=ubuntu-xenial-heavy/54/parsed_console/)
By fixing the PCL version to 1.9.1 the issue should be solved.

### CODE REVIEW

**Comment by ffurrer** [comment]
@ntonci do you remember why you switched to master in https://github.com/ethz-asl/pcl_catkin/commit/2a91b9a6e84571fa12a091c693afd581ba75aac9?

**Comment by margaritaG** [comment]
test this please

**Comment by margaritaG** [comment]
Tests should pass as soon as @ffurrer approves https://github.com/ethz-asl/perception_pcl/pull/4 and the _perception_pcl_ submodule is set to the right commit.

**Comment by ntonci** [comment]
@ffurrer I guess we switched because the fix for ply file loading was merged in master

**Comment by kunaltyagi** [comment]
Hi, I'm here from the PCL repo. PCL is still using boost pointers and the efforts are underway to convert all references to `boost::smart_ptr` to `Class::SmartPtr`, with `using Class::SmartPtr = boost::smart_ptr` indirectly to enable easy switching from `boost` to `std` at **some stage.** not yet.

The tests should not be failing yet. Could you please investigate more?

**Comment by taketwo** [comment]
Hi, I'm also a PCL maintainer. One of the goals in our smart pointer transition project is to *not* break any user code. We thus would appreciate if you indeed investigate more and let us know what exactly is broken for you so we can un-break it before the 1.10 release.

**Comment by margaritaG** [comment]
Hi @kunaltyagi @taketwo 

I have assumed that it was the https://github.com/PointCloudLibrary/pcl/pull/3486 that broke our builds because our nightly builds started showing a related error exactly after that PR was merged into PCL master.

The error message is 

```
/home/jenkins/workspace/pcl_catkin_pull_requests/label/ubuntu-xenial-heavy/src/perception_pcl/pcl_ros/include/pcl_ros/point_cloud.h:79:37: error: no match for 'operator=' (operand types are 'std::shared_ptr<std::vector<pcl::detail::FieldMapping> >' and 'boost::shared_ptr<std::vector<pcl::detail::FieldMapping> >')
       pcl::detail::getMapping(*msg) = mapping_;
```

for [this line of code](https://github.com/ethz-asl/perception_pcl/blob/a7a1e4ff219e01aa362e8e18fd9779a88edb0154/pcl_ros/include/pcl_ros/point_cloud.h#L79).

I have then compared the PCL documentation for the failing method (`pcl::detail::getMapping`) across the [latest PCL trunk](http://docs.pointclouds.org/trunk/namespacepcl_1_1detail.html#ab721eea8d6513ecfe4613fa76e854fb6) and [PCL 1.9.1](http://docs.pointclouds.org/1.9.1/namespacepcl_1_1detail.html#a7d6f4ec10e468cae6d75bad9a54cecff) and what I see is that in 1.9.1 getMapping used to return `boost::shared_ptr< pcl::MsgFieldMap > &` while now it returns `std::shared_ptr< pcl::MsgFieldMap > &`, and because our code was expecting the former, the latest master breaks our code.

It looks very similar to the undesirable effects you have described in https://github.com/PointCloudLibrary/pcl/issues/2792#issuecomment-456875080.

What are your thoughts about this?

**Comment by taketwo** [comment]
Hey, thanks for the information. You are right, https://github.com/PointCloudLibrary/pcl/pull/3486 was indeed a breaking change. The reason why we merged it is because the function `getMapping()` lives in `detail` namespace, so we assumed it's not a part of the public library API and thus in principle should not be used by client code. Apparently, this is not the case.

@SergioRAgostinho have a look at [this file](https://github.com/ros-perception/perception_pcl/blob/melodic-devel/pcl_ros/include/pcl_ros/point_cloud.h). I think we should quickly revert back that change to unbreak `pcl_ros`. Then we can think a proper way to handle the transition given this unexpected usage.

**Comment by SergioRAgostinho** [comment]
Is it worth it though? We are at the final stages of the boost -> std transition.  My next PR was going to target the public API and finish the boost -> std replacements and as I recall we are not planning on keeping boost pointers around in 1.10.

**Comment by taketwo** [comment]
ROS community is perhaps the most important user of PCL. As it stands, we have broken the compilation of their `perception_pcl` package without providing a sane migration path that supports releasing the said package compiled against multiple PCL versions.

Our goal with the migration is to preserve source-level compatibility. In the ideal case, this would mean that a downstream project should be compilable against old and new PCL versions without any changes. Taking into account that this may not be achievable in practice, our relaxed goal is to at least provide a painless migration path for downstream projects that keep them source-compatible with multiple PCL versions. (For example, we can say: "Look, you use plain `boost::shared_ptr`, so you can not compile against master PCL anymore. However, if you replace these plain pointers with `Ptr` typedefs that have been around for ages, your code will be compatible with both old and new PCL).

**Comment by SergioRAgostinho** [comment]
I'm gonna move the discussion back to our issue tracker. Sorry for the noise everyone.

**Comment by margaritaG** [comment]
Looks like this might not be needed after all if https://github.com/ros-perception/perception_pcl/pull/258 will actually unbreak pcl_ros with PCL master. I'll check once that is merged.

**Comment by margaritaG** [comment]
test this please

**Comment by margaritaG** [comment]
Solved by https://github.com/ethz-asl/pcl_catkin/pull/23.

**Pull request closed without merging**
