### PR TITLE
Feature/cleanups minor fix and enable cpp11

### PR DESCRIPTION
**Pull request by HannesSommer**
@ffurrer, the commits are individual suggestions to merge into master. As I don't know how this is used I cannot decide what is compatible with this usage.

### CODE REVIEW

**Comment by ntonci** [comment]
@elenastumm Does this work, can it be merged?

**Comment by elenastumm** [comment]
I believe everything is working for us. I guess @HannesSommer was thinking about waiting for @ffurrer  to check it over, or for further testing? From my perspective everything is ok to be merged though.

**Comment by rdube** [comment]
Works fine on my side!! :dancing_men:

**Comment by HannesSommer** [comment]
My biggest concern is about how the master is currently used because braking existing stuff isn't nice. And I reckoned that @ffurrer knows best about the usage. Still it doesn't seem to be used that much in an incompatible way to the proposed changes (most severe is probably the c++11). Otherwise somebody would probably have complaint already. IMO we can merge this. If problems arise there is still the possibility of partial revert on master and a new split for those that need c++11, like EUROPA2 calibration or segmatch.

**Comment by ffurrer** [comment]
lgtm

**Pull request merged**
